version: '2'
services:
  kong:
    build:
      context: .
      dockerfile: Dockerfile_kong
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: cassandra-db
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    depends_on:
      - cassandra-db
    volumes:
      - .:/opt/scripts
    command: ["/opt/scripts/wait-for-cassandra.sh", "cassandra-db", "9042", "&&", "kong", "start"]
  cassandra-db:
    image: cassandra:2.2
    ports:
      - 9042:9042
